#include "gpio_setup.h"
#include "AS5600.h"

#define LED_BUILTIN_PIN_Pos 3U
#define LED_BUILTIN_PORT GPIOB

void GPIO_Init(void)
{
    RCC->AHB2ENR |= RCC_AHB2ENR_GPIOBEN;
    RCC->AHB2ENR |= RCC_AHB2ENR_GPIOAEN;

    AS5600_DIR_PORT->MODER |= (0x01U << AS5600_DIR_PIN_Pos * 2U);
    AS5600_DIR_PORT->OSPEEDR |= (0x01U << AS5600_DIR_PIN_Pos * 2U);
    AS5600_DIR_PORT->PUPDR |= (0x01U << AS5600_DIR_PIN_Pos * 2U);
    
    LED_BUILTIN_PORT->MODER |= (0x01U << LED_BUILTIN_PIN_Pos * 2U);
    LED_BUILTIN_PORT->OSPEEDR |= (0x01U << LED_BUILTIN_PIN_Pos * 2U);
}
