#include "gpio_setup.h"
#include "AS5600.h"

#define PIN_MODE_INPUT 0x00U
#define PIN_MODE_OUTPUT 0x01U
#define PIN_MODE_ALTERNATE 0x02U
#define CLEAR_BITS 0x03U

#define LED_BUILTIN_PIN_Pos 3U
#define LED_BUILTIN_PORT GPIOB

void GPIO_Init(void)
{
    RCC->AHB2ENR |= RCC_AHB2ENR_GPIOBEN;
    RCC->AHB2ENR |= RCC_AHB2ENR_GPIOAEN;

    AS5600_DIR_PORT->MODER &= ~(CLEAR_BITS << AS5600_DIR_PIN_Pos * 2U);
    AS5600_DIR_PORT->MODER |= (PIN_MODE_OUTPUT << AS5600_DIR_PIN_Pos * 2U);
    LED_BUILTIN_PORT->MODER &= ~(CLEAR_BITS << LED_BUILTIN_PIN_Pos * 2U);
    LED_BUILTIN_PORT->MODER |= (PIN_MODE_OUTPUT << LED_BUILTIN_PIN_Pos * 2U);

    AS5600_DIR_PORT->OSPEEDR &= ~(CLEAR_BITS << AS5600_DIR_PIN_Pos * 2U);
    AS5600_DIR_PORT->OSPEEDR |= (0x01U << AS5600_DIR_PIN_Pos * 2U);
    LED_BUILTIN_PORT->OSPEEDR &= ~(CLEAR_BITS << LED_BUILTIN_PIN_Pos * 2U);
    LED_BUILTIN_PORT->OSPEEDR |= (0x01U << LED_BUILTIN_PIN_Pos * 2U);

    AS5600_DIR_PORT->PUPDR &= ~(CLEAR_BITS << AS5600_DIR_PIN_Pos * 2U);
    AS5600_DIR_PORT->PUPDR |= (0x01U << AS5600_DIR_PIN_Pos * 2U);
}
